[project]
name = "bubi-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlflow-skinny==2.15.1",
    "prophet==1.1.5",
    "pyspark==3.5.4",
    "pytest>=8.4.1",
    "scikit-learn==1.6.1",
]
