# The main job for bubi_prediction.
resources:
  jobs:
    train:
      name: train

      trigger:
        # Run this job every day, exactly one day from the last run; see https://docs.databricks.com/api/workspace/jobs/create#trigger
        periodic:
          interval: 1
          unit: DAYS

      tasks:
        - task_key: ingestion
          existing_cluster_id: ${var.cluster}
          notebook_task:
            notebook_path: ../src/data_processing.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              volume: ${var.volume}
              checkpoint_volume_name: ${resources.volumes.checkpoint_volume.name}
        - task_key: baseline
          existing_cluster_id: ${var.cluster}
          depends_on:
            - task_key: ingestion
          notebook_task:
            notebook_path: ../src/baseline_model.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              train_cutoff: ${var.train_cutoff}
              station_id: ${var.station_id}
              experiment_name: ${var.experiment_name}
              model_name: ${var.model_name}
              force_retrain: "False"
        - task_key: training
          existing_cluster_id: ${var.cluster}
          depends_on:
            - task_key: baseline
          notebook_task:
            notebook_path: ../src/training.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              train_cutoff: ${var.train_cutoff}
              station_id: ${var.station_id}
              experiment_name: ${var.experiment_name}
              model_name: ${var.model_name}
        - task_key: promotion
          existing_cluster_id: ${var.cluster}
          depends_on:
            - task_key: training
          notebook_task:
            notebook_path: ../src/promotion.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              model_name: ${var.model_name}
              previous_run_id: "{{tasks.training.values.previous_run_id}}"
        - task_key: challenger_validation
          existing_cluster_id: ${var.cluster}
          depends_on:
            - task_key: promotion
          notebook_task:
            notebook_path: ../src/challenger_validation.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              model_name: ${var.model_name}
        